### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by premnirmal** [cbedoy/CBChatHead#3]
I see some classes in this project that are taken from www.github.com/premnirmal/magnet such as:
- `RemoveView.java`
- `SimpleAnimator.java`
- `FlingListener.java`

This violates the license copyright.
It will be appreciated if there were acknowledgements added to the README and the class.

**Comment by cbedoy** [comment]
Yes, I'm sorry but I never imagine that this repo will have views hahaha

Sorry bro, I just added your reference, I remember this project when I start to do experiments.

I saw your project is so advanced 👍

**Comment by premnirmal** [comment]
Thanks for the update! Appreciate it.
